name: test_example_server

on:
  push:
    paths:
      - '.github/workflows/test_example_server.yml'
      - 'example_server/**'
      - 'test_server/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      #- name: make test_example_server
      - run: make test_example_server

      #- name: upload-artifact test reports
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: test_server/reports/
          retention-days: 90

      # https://github.com/marketplace/actions/test-reporting
      #- name: Test Report
      - uses: phoenix-actions/test-reporting@v8
        id: test-report   # Set ID reference for step
        if: always()
        with:
          name: junit
          path: test_server/reports/*.xml
          reporter: java-junit
