name: test_example_client

on:
  - workflow_dispatch  # Disable running on every commit because this job downloaded a 4gb image and github actions have no cache
  #push:
  #  paths:
  #    - 'example_client/**'
  #    - 'test_client/**'

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      #- name: checkout
      - uses: actions/checkout@main

      #- name: make test_example_client
      - run: make test_example_client

      #- name: upload-artifact test reports
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress
          path: test_client/reports/
          retention-days: 90

      # https://github.com/marketplace/actions/test-reporting
      #- name: Test Report
      - uses: phoenix-actions/test-reporting@v8
        id: test-report   # Set ID reference for step
        if: always()
        with:
          name: test_client
          path: test_client/reports/*.xml
          reporter: java-junit
